# Generated by Django 5.0 on 2024-02-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_onlineuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineuser',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
